2025-02-14 04:30:11,830 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2025-02-14 04:30:11,830 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Configure stats pid to 883041
2025-02-14 04:30:11,830 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Loading settings from /n/home00/sumedh/.config/wandb/settings
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Loading settings from /n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/wandb/settings
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'experiments/expt16_intrindicdimX/trainmodel.py', 'program_abspath': '/n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/trainmodel.py', 'program': '/n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/trainmodel.py'}
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_init.py:_log_setup():520] Logging user logs to /n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/wandb/run-20250214_043011-1wmivf1t/logs/debug.log
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_init.py:_log_setup():521] Logging internal logs to /n/home00/sumedh/spmax_sae/experiments/expt16_intrindicdimX/wandb/run-20250214_043011-1wmivf1t/logs/debug-internal.log
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_init.py:init():560] calling init triggers
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'seed_id': 1, 'device': 'cuda', 'wandbprojectname': 'intrinsic_dimX', 'experiment_date': 'today', 'sae_type': 'topk_relu', 'weight_init': 'random', 'normalize_decoder': True, 'resample_deadneurons': False, 'sae_width': 512, 'kval_topk': 16, 'dataset': '128dgaussian_intrinsicdim', 'num_concepts': 5, 'return_concept_loss': True, 'data_dim': 128, 'save_checkpoints': True, 'batch_size': 2048, 'regularizer': 'auxloss', 'encoder_reg': True, 'gamma_reg': 1.0, 'optimizer': 'adam', 'clip_grad': True, 'online_training': True}
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_init.py:init():610] starting backend
2025-02-14 04:30:11,831 INFO    MainThread:883041 [wandb_init.py:init():614] setting up manager
2025-02-14 04:30:11,852 INFO    MainThread:883041 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-14 04:30:11,854 INFO    MainThread:883041 [wandb_init.py:init():622] backend started and connected
2025-02-14 04:30:11,897 INFO    MainThread:883041 [wandb_init.py:init():711] updated telemetry
2025-02-14 04:30:12,038 INFO    MainThread:883041 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-02-14 04:30:12,337 INFO    MainThread:883041 [wandb_run.py:_on_init():2402] communicating current version
2025-02-14 04:30:12,391 INFO    MainThread:883041 [wandb_run.py:_on_init():2411] got version response upgrade_message: "wandb version 0.19.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-02-14 04:30:12,391 INFO    MainThread:883041 [wandb_init.py:init():795] starting run threads in backend
2025-02-14 04:30:17,315 INFO    MainThread:883041 [wandb_run.py:_console_start():2380] atexit reg
2025-02-14 04:30:17,316 INFO    MainThread:883041 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-02-14 04:30:17,316 INFO    MainThread:883041 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-02-14 04:30:17,316 INFO    MainThread:883041 [wandb_run.py:_redirect():2325] Redirects installed.
2025-02-14 04:30:17,320 INFO    MainThread:883041 [wandb_init.py:init():838] run started, returning control to user process
2025-02-14 04:38:59,795 WARNING MsgRouterThr:883041 [router.py:message_loop():77] message_loop has been closed
